name: deploy

on:
  push:
    branches:
      - 'laravel-beta'

jobs:
  deploy_staging:
    uses: ./.github/workflows/deploy.yml
    with:
      envname: beta
      docker_tag: beta
      docker_port: 8002
    secrets:
      host: ${{secrets.HOST}}
      user: ${{secrets.USER}}
      private_key: ${{secrets.PRIVATE_KEY}}



